name: "auto-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel log21>=1.5.2 numpy==1.22.0 pyinstaller==4.7 pyopencl requests==2.27.1 websocket==0.2.1
      - name: Build
        run: |
          pyinstaller miner.py -F -c --collect-all pyopencl --collect-all certifi --add-data sha256.cl:opencl_program --add-data hash_solver.cl:opencl_program --hidden-import websocket-client -i icon.ico
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-autobuild-linux"
          title: "Auto Build"
          files: |
            dist/*
  pre-release-windows:
    name: "Auto Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel log21>=1.5.2 numpy==1.22.0 pyinstaller==4.7 pyopencl requests==2.27.1 websocket==0.2.1
      - name: Build
        run: |
          pyinstaller miner.py -F -c --collect-all pyopencl --collect-all certifi --add-data sha256.cl;opencl_program --add-data hash_solver.cl;opencl_program --hidden-import websocket-client -i icon.ico
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-autobuild-win"
          title: "Auto Build"
          files: |
            dist/*